I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 504, in script
    gg "Тешь себя, ведь ты 100% можешь не выходить за рамки. Тешь себя, что ты прожил немногим дольше людей, которые закончили свои полёты раньше тебя."
ValueError: unsupported format character '?' (0x43c) at index 24

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 504, in script
    gg "Тешь себя, ведь ты 100% можешь не выходить за рамки. Тешь себя, что ты прожил немногим дольше людей, которые закончили свои полёты раньше тебя."
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\ast.py", line 615, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\User\Desktop\Book\renpy-8.2.0-sdk\renpy\exports.py", line 1482, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character '?' (0x43c) at index 24

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.0.24012702
BadSingular 1.0
Thu May 16 21:08:23 2024
