I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 50, in script call
    call kill_effi
  File "game/Persona/Ivents/house_murder.rpy", line 32, in script call
    call repeat_animation(2, morher=True)
  File "game/Persona/Ivents/house_murder.rpy", line 4, in script
    label repeat_animation(n, mother = False):
TypeError: Unexpected keyword arguments: 'morher'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 50, in script call
    call kill_effi
  File "game/Persona/Ivents/house_murder.rpy", line 32, in script call
    call repeat_animation(2, morher=True)
  File "game/Persona/Ivents/house_murder.rpy", line 4, in script
    label repeat_animation(n, mother = False):
  File "D:\Soft\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 1081, in execute
    values = apply_arguments(self.parameters, renpy.store._args, renpy.store._kwargs)
  File "D:\Soft\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 296, in apply_arguments
    return parameters.apply(args, kwargs, ignore_errors)
  File "D:\Soft\RenPy\renpy-8.1.3-sdk\renpy\ast.py", line 281, in apply
    raise TypeError(
TypeError: Unexpected keyword arguments: 'morher'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Zero Keep Out 1.0
Sun May 26 18:47:27 2024
